openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/users/:
    get:
      operationId: List All Users
      description: "\u0412\u044C\u044E\u0441\u0435\u0442 \u0434\u043B\u044F \u043F\
        \u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u0435\u0439."
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
          description: ''
      tags:
      - api
    post:
      operationId: Register
      description: "\u0412\u044C\u044E\u0441\u0435\u0442 \u0434\u043B\u044F \u043F\
        \u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u0435\u0439."
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserCreate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserCreate'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserCreate'
          description: ''
      tags:
      - api
  /api/users/friends/:
    get:
      operationId: Get List Of Friends
      description: "\u041C\u0435\u0442\u043E\u0434 \u043F\u0440\u043E\u0441\u043C\u043E\
        \u0442\u0440\u0430 \u0441\u043F\u0438\u0441\u043A\u0430 \u0434\u0440\u0443\
        \u0437\u0435\u0439"
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
      tags:
      - api
  /api/users/me/:
    get:
      operationId: Current User Info
      description: "\u0412\u044C\u044E\u0441\u0435\u0442 \u0434\u043B\u044F \u043F\
        \u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u0435\u0439."
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
      tags:
      - api
  /api/users/{id}/:
    get:
      operationId: Get User Info By Id
      description: "\u0412\u044C\u044E\u0441\u0435\u0442 \u0434\u043B\u044F \u043F\
        \u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u0435\u0439."
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u043F\u043E\u043B\u044C\
          \u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044C."
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
      tags:
      - api
  /api/friend_requests/outgoing/:
    get:
      operationId: Get Your Outgoing Friend Requests
      description: "\u0412\u044C\u044E\u0441\u0435\u0442 \u043F\u0440\u043E\u0441\u043C\
        \u043E\u0442\u0440\u0430 \u0441\u043F\u0438\u0441\u043A\u0430 \u0438\u0441\
        \u0445\u043E\u0434\u044F\u0449\u0438\u0445 \u0437\u0430\u044F\u0432\u043E\u043A\
        ."
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FriendRequestBy'
          description: ''
      tags:
      - api
  /api/friend_requests/incoming/:
    get:
      operationId: Get Your Incoming Friend Requests
      description: "\u0412\u044C\u044E\u0441\u0435\u0442 \u043F\u0440\u043E\u0441\u043C\
        \u043E\u0442\u0440\u0430 \u0441\u043F\u0438\u0441\u043A\u0430 \u0438\u0441\
        \u0445\u043E\u0434\u044F\u0449\u0438\u0445 \u0437\u0430\u044F\u0432\u043E\u043A\
        ."
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FriendRequestTo'
          description: ''
      tags:
      - api
  /api/auth/jwt/create/:
    post:
      operationId: Get Auth Token
      description: 'Takes a set of user credentials and returns an access and refresh
        JSON web

        token pair to prove the authentication of those credentials.'
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenObtainPair'
          description: ''
      tags:
      - api
  /api/auth/jwt/refresh/:
    post:
      operationId: Referesh Auth Token
      description: 'Takes a refresh type JSON web token and returns an access type
        JSON web

        token if the refresh token is valid.'
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
      tags:
      - api
  /api/users/{id}/add_friend/:
    post:
      operationId: Add Friend
      description: "\u041C\u0435\u0442\u043E\u0434 \u0434\u043E\u0431\u0430\u0432\u043B\
        \u0435\u043D\u0438\u044F \u0434\u0440\u0443\u0433\u0430."
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u043F\u043E\u043B\u044C\
          \u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044C."
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
      tags:
      - api
  /api/friend_requests/incoming/{id}/accept/:
    post:
      operationId: Accept Friend Request
      description: "\u041C\u0435\u0442\u043E\u0434 \u043F\u043E\u0434\u0442\u0432\u0435\
        \u0440\u0436\u0434\u0435\u043D\u0438\u044F \u0437\u0430\u044F\u0432\u043A\u0438\
        ."
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FriendRequestTo'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/FriendRequestTo'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/FriendRequestTo'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FriendRequestTo'
          description: ''
      tags:
      - api
  /api/friend_requests/incoming/{id}/decline/:
    post:
      operationId: Decline Friend Request
      description: "\u041C\u0435\u0442\u043E\u0434 \u043F\u043E\u0434\u0442\u0432\u0435\
        \u0440\u0436\u0434\u0435\u043D\u0438\u044F \u0437\u0430\u044F\u0432\u043A\u0438\
        ."
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FriendRequestTo'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/FriendRequestTo'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/FriendRequestTo'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FriendRequestTo'
          description: ''
      tags:
      - api
  /api/users/{id}/delete_friend/:
    delete:
      operationId: Delete Friend
      description: "\u041C\u0435\u0442\u043E\u0434 \u0443\u0434\u0430\u043B\u0435\u043D\
        \u0438\u044F \u0434\u0440\u0443\u0433\u0430."
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u043F\u043E\u043B\u044C\
          \u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044C."
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          pattern: ^[a-zA-z0-9]
          maxLength: 150
        friendship_status:
          type: string
          readOnly: true
      required:
      - username
    FriendRequestBy:
      type: object
      properties:
        requested_to:
          type: string
      required:
      - requested_to
    FriendRequestTo:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        requested_by:
          type: string
      required:
      - requested_by
    TokenCreate:
      type: object
      properties:
        password:
          type: string
        username:
          type: string
    TokenObtainPair:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
          writeOnly: true
      required:
      - username
      - password
    TokenRefresh:
      type: object
      properties:
        refresh:
          type: string
        access:
          type: string
          readOnly: true
      required:
      - refresh
    TokenVerify:
      type: object
      properties:
        token:
          type: string
      required:
      - token
    UserCreate:
      type: object
      properties:
        email:
          type: string
          format: email
          maxLength: 254
        username:
          type: string
          pattern: ^[a-zA-z0-9]
          maxLength: 150
        first_name:
          type: string
          maxLength: 150
        last_name:
          type: string
          maxLength: 150
        password:
          type: string
          writeOnly: true
      required:
      - username
      - password
